name: Deploy to DigitalOcean

on:
  push:
    branches: [ logging ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_REGISTRY_TOKEN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Build and Push Docker images
        env:
          REGISTRY: registry.digitalocean.com
          REPOSITORY: expense-tracker
        run: |
          # Build and push API image
          docker build \
            --build-arg MONGO_USER=${{ secrets.MONGO_USER }} \
            --build-arg MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --build-arg FRONTEND_URL=${{ secrets.FRONTEND_URL }} \
            -t $(echo $REGISTRY)/$(echo $REPOSITORY)/expense-api:$(echo $GITHUB_SHA | head -c7) \
            -t $(echo $REGISTRY)/$(echo $REPOSITORY)/expense-api:latest \
            .
          
          docker push $(echo $REGISTRY)/$(echo $REPOSITORY)/expense-api:$(echo $GITHUB_SHA | head -c7)
          docker push $(echo $REGISTRY)/$(echo $REPOSITORY)/expense-api:latest

          # Build and push MongoDB image
          docker build \
            --build-arg MONGO_USER=${{ secrets.MONGO_USER }} \
            --build-arg MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
            -f Dockerfile.mongo \
            -t $(echo $REGISTRY)/$(echo $REPOSITORY)/mongo:$(echo $GITHUB_SHA | head -c7) \
            -t $(echo $REGISTRY)/$(echo $REPOSITORY)/mongo:latest \
            .
          
          docker push $(echo $REGISTRY)/$(echo $REPOSITORY)/mongo:$(echo $GITHUB_SHA | head -c7)
          docker push $(echo $REGISTRY)/$(echo $REPOSITORY)/mongo:latest

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DO_SSH_KEY }}
          known_hosts: 'placeholder'
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to DigitalOcean
        env:
          REGISTRY: registry.digitalocean.com
          REPOSITORY: test-apps
        run: |
          ssh root@${{ secrets.DO_HOST }} << ENDSSH
            cd /opt/expense-tracker
            
            # Login to DO registry
            doctl registry login --expiry-seconds 600
            
            # Stop and remove existing containers
            docker-compose down
            
            # Pull latest images
            docker pull $(echo $REGISTRY)/$(echo $REPOSITORY)/expense-api:latest
            docker pull $(echo $REGISTRY)/$(echo $REPOSITORY)/mongo:latest
            
            # Start containers
            docker-compose up -d
            
            # Clean up
            docker system prune -f
            
            # Wait for application to be ready
            echo "Waiting for application to start..."
            sleep 20
            
            # Check if application is running
            if curl -f http://localhost:4000/health; then
              echo "Deployment successful!"
            else
              echo "Deployment failed!"
              exit 1
            fi
          ENDSSH